#include <stdio.h>

int * gen_arr(void) {
    int ret[3];
    ret[0] = 1;
    ret[1] = 2;
    ret[2] = 3;
    return ret;
}

int main(void) {
    //int arr[5];

    //arr[3] = 42;
    
    //printf("Array holds 5 integers at indeces 0..4\n");
    //printf("Value at index 3 is: %d\n", arr[3]);
    //printf("Value at invalid index 6 is: %d\n", arr[6]);

    int * insecure_arr = gen_arr();

    printf("Array generated by another function:\n");
    printf("Index 0 contains: %d\n", insecure_arr[0]);
    
    return 0;
}
